# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_btn_gen_keys_2(object):
    def setupUi(self, btn_gen_keys_2):
        btn_gen_keys_2.setObjectName("btn_gen_keys_2")
        btn_gen_keys_2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(btn_gen_keys_2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 40, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(460, 90, 93, 28))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 150, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 280, 55, 16))
        self.label_3.setObjectName("label_3")
        self.txt_infor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_infor.setGeometry(QtCore.QRect(180, 140, 491, 81))
        self.txt_infor.setObjectName("txt_infor")
        self.txt_sign = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(180, 270, 491, 87))
        self.txt_sign.setObjectName("txt_sign")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(180, 410, 93, 28))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(520, 410, 93, 28))
        self.btn_verify.setObjectName("btn_verify")
        btn_gen_keys_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(btn_gen_keys_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        btn_gen_keys_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(btn_gen_keys_2)
        self.statusbar.setObjectName("statusbar")
        btn_gen_keys_2.setStatusBar(self.statusbar)

        self.retranslateUi(btn_gen_keys_2)
        QtCore.QMetaObject.connectSlotsByName(btn_gen_keys_2)

    def retranslateUi(self, btn_gen_keys_2):
        _translate = QtCore.QCoreApplication.translate
        btn_gen_keys_2.setWindowTitle(_translate("btn_gen_keys_2", "MainWindow"))
        self.label.setText(_translate("btn_gen_keys_2", "ECC CIPHER"))
        self.btn_gen_keys.setText(_translate("btn_gen_keys_2", "Generate Keys"))
        self.label_2.setText(_translate("btn_gen_keys_2", "Information"))
        self.label_3.setText(_translate("btn_gen_keys_2", "Signature"))
        self.btn_sign.setText(_translate("btn_gen_keys_2", "Sign"))
        self.btn_verify.setText(_translate("btn_gen_keys_2", "Verify"))
